HeaClub/HeaClub/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.static import serve

from HeaClub import settings
from HeaClub.settings import MEDIA_ROOT
from users.views import login, RegisterView, LoginView, IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',IndexView.as_view(),name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('course/', include('course.urls', namespace='course')),
    path('teacher/', include('teachers.urls', namespace='teacher')),
    path('users/', include('users.urls',namespace='users')),
    path('bbs/', include('bbs.urls', namespace='bbs')),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HeaClub/apps/bbs/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path

from bbs.views import BIndexView, AddTieView, TieDetailView, CommentView

app_name="bbs"
urlpatterns = [
    path('', BIndexView.as_view(), name="index"),
    path('add_topic', AddTieView.as_view(), name="add_topic"),
    re_path('detail/(?P<topic_id>\d+)/', TieDetailView.as_view(), name="detail"),
    path('comment', CommentView.as_view(), name="comment"),
    ]

HeaClub/apps/course/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path

from course.views import CourseListView, CourseDetailView

app_name = 'course'

urlpatterns = [
    # 课程列表
    path('list/<pindex>', CourseListView.as_view(), name='course_list'),
    re_path('course_detail/(?P<course_id>\d+)/', CourseDetailView.as_view(), name='course_detail'),
]

HeaClub/apps/teachers/urls.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView

from teachers.views import TeacherListView, TeacherinfoView, ReleaseCourse, AddCouListView, TeacherDetailView, \
    AddFavView, SelStuView, MyFanView, UpCourse, CourseDe, UpCouListView, DeCouListView, DeleteBbs

app_name = 'teacher'
urlpatterns = [
    path('list/', TeacherListView.as_view(), name="teacher_list"),#教练列表
    path('tinfo', TeacherinfoView.as_view(), name="teacher_info"),#教练个人中心
    path('relcou', ReleaseCourse.as_view(), name="relcou"),#课程管理
    path('addclist', AddCouListView.as_view(), name="addclist"),#课程表
    path('upclist', UpCouListView.as_view(), name="upclist"),#课程表
    path('declist', DeCouListView.as_view(), name="declist"),  # 课程表
    re_path('detail/(?P<teacher_id>\d+)/',TeacherDetailView.as_view(), name="detail"),#教练详情
    path('addfav', AddFavView.as_view(), name="addfav"),#
    path('selstu', SelStuView.as_view(), name="selstu"),#查询学员
    path('myfan', MyFanView.as_view(), name="myfan"),#我的粉丝
    path('upcou', UpCourse.as_view(), name="upcou"),#课程修改
    path('coudelete', CourseDe.as_view(), name="coudelete"),#课程删除
    path('deletebbs', DeleteBbs.as_view(), name="deletebbs"),  # 删除帖子


]

HeaClub/apps/users/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from users.views import UserinfoView, UploadImageView, MemberView, SignView, LogoutView, \
    MyFavTeacherView, MyFavCourseView, PayResultView

app_name="users"
urlpatterns = [
    path('info', UserinfoView.as_view(), name="user_info"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('image/upload/', UploadImageView.as_view(), name="image_upload"),
    path('member', MemberView.as_view(), name="member"),
    path('sign', SignView.as_view(), name="sign"),
    path('myfavtea', MyFavTeacherView.as_view(), name="myfavtea"),
    path('myfavcou', MyFavCourseView.as_view(), name="myfavcou"),
    path('pay_result', PayResultView.as_view(), name="pay_result"),

]

HeaClub/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>链接失效</p>
</body>
</html>

HeaClub/templates/bbs_add.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    发布帖子
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css"
          href="{% static '/ueditor/UE/third-party/SyntaxHighlighter/shCoreDefault.css' %}">
    <script type="text/javascript" src="{% static '/ueditor/UE/third-party/SyntaxHighlighter/shCore.js' %}"></script>
    <script type="text/javascript" src="{% static '/ueditor/UE/ueditor.config.js' %}"></script>
    <script type="text/javascript" src="{% static '/ueditor/UE/ueditor.all.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/ueditor/UE/lang/zh-cn/zh-cn.js' %}"></script>

    <script type="text/javascript">
        var ue = UE.getEditor('editor');
        SyntaxHighlighter.all();
    </script>
{% endblock %}
{% block custom_bread %}
    <div class="wp">
        <ul class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'bbs:index' %}">论坛</a>></li>
            <li>发布帖子</li>
        </ul>
    </div>
{% endblock %}
{% block content %}
    <section>
        <div class="wp">
            <div class="list">
                <div class="left layout">
                    <div class="head" style="border:1px solid #c0bcb6;">
                        <h1 class="tab_header" style="margin-left: 5px">发布帖子</h1>
                    </div>
                    <div id="inWindow">
                        <div class="tab_cont" id="" content="">
                            <form action="{% url 'bbs:add_topic' %}" method="post">
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="input-group-addon" style="font-size: 20px">标题:</span>
                                        <input type="text" class="form-control" name="title"
                                               style="margin-left: 2px;width: 180px;height: 30px">
                                    </div>
                                </div>
                                <div class="form-group" style="margin-top: 15px">
                                    <div class="input-group">
                                        <span class="input-group-addon" style="font-size: 20px">板块:</span>
                                        <select name="board_id" class="form-control" style="margin-left: 2px;width: 180px;height: 30px">

                                            {% for board in boards %}
                                                <option value="{{ board.id }}">{{ board.name }}</option>
                                            {% endfor %}

                                        </select>
                                    </div>
                                </div>
                                 <div class="form-group" style="margin-top: 15px">
                                    <div class="input-group">
                                        <span class="input-group-addon" style="font-size: 20px">内容:</span>
                                     <script id="editor" type="text/plain" name="content"></script>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="submit" style="background: #0b92e0;width: 80px;height: 30px" id="submit-btn">发布帖子</button>
                                </div>
                                {% csrf_token %}
                            </form>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

HeaClub/templates/index.html
{% extends 'base.html' %}
{% block title %}网络健身平台{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}

{% block content %}
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% if all_banners %}
                            {% for banner in all_banners %}
                            <li>
                                    <a href="{{ banner.url }}">
                                        <img width="1200" height="400" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                            {% endfor %}
                        {% else %}
                                <li>
                                    <a href="/static/images/b1.jpg">
                                        <img width="1200" height="400" src="{% static "/images/b1.jpg" %}" />
                                    </a>
                                </li>
                                 <li>
                                    <a href="/static/images/b2.jpg">
                                        <img width="1200" height="400" src="{% static "/images/b2.jpg" %}" />
                                    </a>
                                </li>
                                 <li>
                                    <a href="/static/images/b3.jpg">
                                        <img width="1200" height="400" src="{% static "/images/b3.jpg" %}" />
                                    </a>
                                </li>
                        {% endif %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>
				</div>
			</div>
	<section>
		<div class="module">
			<div class="wp" >
                <div style="margin-top: 15px">
                <img style="height: 15px; vertical-align: middle;width:500px" src="{% static "/images/page.png" %}" />
                    <span style="font-size: 30px;font-weight:bold;">金牌课程</span>
                <img style="height: 15px; vertical-align: middle;width: 500px" src="{% static "/images/page.png" %}" />
                </div>
				<div class="module1 eachmod">
					<div class="right group_list">
                            {% for course in all_course %}
                            <div class="module1_{{ forloop.counter|add:4 }} box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2 title="{{ course.name }}">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">热量：{{ course.heat }}千卡</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>
                                    <span class="star fr">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                            {% endfor %}
					</div>
				</div>

			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				      <div style="margin-top: 15px">
                <img style="height: 15px; vertical-align: middle;width:500px" src="{% static "/images/page.png" %}" />
                    <span style="font-size: 30px;font-weight:bold;">专业教练</span>
                <img style="height: 15px; vertical-align: middle;width: 500px" src="{% static "/images/page.png" %}" />
                </div>
				<div class="module3 eachmod">

					<div class="right">
						<ul>
                            {% for teacher in all_teacher %}
                                <li class="{% if forloop.counter|divisibleby:4 %}five{% endif %}">
                                    <a href="{% url 'teacher:detail' teacher.user.id %}">
                                        <div class="company">
                                            <img width="232" height="190" src="{{ MEDIA_URL }}{{ teacher.user.image }}"/>
                                             <h2>工号：{{ teacher.user.username}}</h2>
{#                                    <span class="fl">难度：<i class="key">11</i></span>#}
{#                                    <span class="fr">学习人数：11</span>#}
                                             </div>

                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

HeaClub/templates/teacher-base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}个人资料{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>

{% block custom_css %}
{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
  {% block head %}{% endblock %}
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
 			<div class="top">
				<div class="wp">
							<div class="fl"><p style="	font-size: 18px;">健身平台欢迎你！</p></div>
					<!--登录后跳转-->
       {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd><a style="color: white" class="fr" href="{% url 'users:logout' %}">退出</a></dd>
                                <dd>{% if request.user.type == 'tea' %}
                                    <a class="personcenter fl" style="color: white"
                                       href="{% url 'teacher:teacher_info' %}">个人中心</a>
                                {% else %}
                                    <a class="personcenter fl" style="color: white" href="{% url 'users:user_info' %}">个人中心</a>
                                {% endif %}</dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                <dd style="margin-left: 0px;">{{ user.username }}</dd>

                            </dl>
                        </div>
                    {% else %}
                        <a style="color:white ;font-size:15px " class="fr registerbtn"
                           href="{% url 'register' %}">免费注册</a>
                        <a style="color:white;font-size:15px" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
                </div>
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="/"><img class="fl" src="/static/images/logo.png"/></a>

                </div>
            </div>
        </div>
    </header>
</section>


<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'teacher:teacher_info' %}">个人中心</a>></li>
                <li>个人信息</li>
            </ul>
        </div>
    </section>
{% endblock %}
<section>
    <div class="wp list personal_list">
        <div class="left">
            <ul>
                <li class="active2"><a href="{% url 'teacher:teacher_info' %}">个人资料</a></li>
                <li><a href="{% url 'teacher:selstu' %}">查询学员信息</a></li>
                <li><a href="{% url 'teacher:relcou' %}">教程管理</a></li>
                <li><a href="{% url 'teacher:addclist' %}">发布课程表</a></li>
                <li><a href="{% url 'teacher:myfan' %}">我的粉丝</a></li>
                <li><a href="{% url 'teacher:deletebbs' %}">我的帖子</a></li>
            </ul>
        </div>

        {% block right_content %}
            <div class="right">
                <div class="personal_des ">
                    <div class="head" style="border:1px solid #eaeaea;">
                        <h1>个人信息</h1>
                    </div>
                    <div class="inforcon">

                        <div class="left" style="width:242px;">
                            <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                            <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off"
                                  method="post" action="{% url 'users:image_upload' %}" target='frameFile'>
                                <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow"
                                     src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                            </span>
                                    <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                                </label>
                                {% csrf_token %}
                            </form>

                        </div>
                        <form class="perinform" id="jsEditUserForm" autocomplete="off">
                            <ul class="right">
                                <li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                                    <input type="text" name="username" id="username" value="{{ request.user.username }}"
                                           maxlength="10">
                                    <i class="error-tips"></i>
                                </li>
                                <li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                                    <input type="text" id="birthday" name="birthday" value="{{ request.user.birthday }}"
                                           readonly="readonly"/>
                                    <i class="error-tips"></i>
                                </li>
                                <li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
                                    <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="sex" value="male"
                                                                                {% if request.user.gender == 'male' %}checked="checked"{% endif %}>男</label>
                                    <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="sex"
                                                                                      value="female"
                                                                                      {% if request.user.gender == 'female' %}checked="checked"{% endif %}>女</label>
                                </li>
                                <li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                                    <input type="text" name="address" id="address" placeholder="请输入你的地址"
                                           value="{{ request.user.address }}" maxlength="10">
                                    <i class="error-tips"></i>
                                </li>
                                <li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                                    <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码"
                                           value="{{ request.user.mobile }}" maxlength="10">
                                </li>

                                <li class="button heibtn">
                                    <input type="button" id="jsEdit" value="保存">
                                </li>
                            </ul>
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        {% endblock %}

    </div>
</section>


<div class="dialog" id="jsDialog">
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
    <!--提示弹出框-->
    <div class="bidtips dialogbox promptbox" id="jsComfirmDialig">
        <h1>确认提交</h1>
        <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
        <div class="cont">
            <h2>您确认提交吗？</h2>
            <dd class="autoTxtCount">
                <div class="button">
                    <input type="button" class="fl half-btn" value="确定" id="jsComfirmBtn"/>
                    <span class="fr half-btn jsCloseDialog">取消</span>
                </div>
            </dd>
        </div>
    </div>
    <div class="resetpwdbox dialogbox" id="jsResetDialog">
        <h1>修改密码</h1>
        <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
        <div class="cont">
            <form id="jsResetPwdForm" autocomplete="off">
                <div class="box">
                    <span class="word2">新&nbsp;&nbsp;密&nbsp;&nbsp;码</span>
                    <input type="password" id="pwd" name="password1" placeholder="6-20位非中文字符"/>
                </div>
                <div class="box">
                    <span class="word2">确定密码</span>
                    <input type="password" id="repwd" name="password2" placeholder="6-20位非中文字符"/>
                </div>
                <div class="error btns" id="jsResetPwdTips"></div>
                <div class="button">
                    <input id="jsResetPwdBtn" type="button" value="提交"/>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
<div class="bg" id="dialogBg"></div>


<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>
<script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
<script src="{% static 'js/validate.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-user.js' %}"></script>


<script>

    var sta = {

        elem: '#sta_time',
        format: 'YYYY-MM-DD',
        istime: true,
        istoday: false,
        start: laydate.now(0, "YYYY-MM-DD"),

    };

    laydate(sta);


    var end = {

        elem: '#end_time',
        format: 'YYYY-MM-DD',
        istime: true,
        istoday: false,
        start: laydate.now(0, "YYYY-MM-DD"),

    };

    laydate(end);

</script>

</body>
</html>

HeaClub/templates/usercenter-base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
  {% block head %}{% endblock %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}个人资料 {% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>

{% block custom_css %}
{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p style="	font-size: 18px;">健身平台欢迎你！</p></div>
					<!--登录后跳转-->
                        {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                 <dd ><a style="color: white" class="fr" href="{% url 'users:logout' %}">退出</a></dd>
                                       <dd>{% if request.user.type == 'tea' %}
                                         <a class="personcenter fl"  style="color: white" href="{% url 'teacher:teacher_info' %}">个人中心</a>
                                    {% else %}
	                                    <a class="personcenter fl" style="color: white" href="{% url 'users:user_info' %}">个人中心</a>
                                    {% endif %}</dd>
                                <dt ><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                <dd style="margin-left: 0px;">{{ user.username }}</dd>

                            </dl>
                        </div>
                    {% else %}
                        <a style="color:white ;font-size:15px " class="fr registerbtn" href="{% url 'register' %}">免费注册</a>
                        <a style="color:white;font-size:15px" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
				</div>
			</div>

            
    <div class="middle">
        <div class="wp">
            <a href="/"><img class="fl" src="/static/images/logo.png"/></a>
        </div>
    </div>
			</div>
    </header>
</section>



<!--crumbs start-->
{% block custom_bread %}
<section>
	<div class="wp">
		<ul  class="crumbs">
			<li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
			<li>个人信息</li>
		</ul>
	</div>
</section>
{% endblock %}
<section>
	<div class="wp list personal_list">
	<div class="left">
        <ul>
            <li class="active2"><a href="{% url 'users:user_info' %}">
                <img src="/static/images/512/android-contact.png" class="ima">
                个人信息管理</a></li>
            <li ><a href="{% url 'users:member' %}">
             <img src="/static/images/512/social-foursquare-outline.png"class="ima">
                开通会员</a></li>
            <li ><a href="{% url 'users:myfavtea' %}">
                <img src="/static/images/512/compose.png"class="ima">订阅教练</a></li>
            <li ><a href="{% url 'users:myfavcou' %}"> <img src="/static/images/512/ios7-heart.png" class="ima">收藏教程</a></li>
            <li ><a href="{% url 'users:sign' %}"> <img src="/static/images/512/android-calendar.png" class="ima">签到</a></li>
        </ul>
	</div>

    {% block right_content %}
    <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="/user/avatar/upload/" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="/uploads/avatar/default_big.png"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="avatar_url" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label>
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>

			</div>
		</div>
	</div>
    {% endblock %}

	</div>
</section>



<div class="dialog" id="jsDialog">
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
    <!--提示弹出框-->
    <div class="bidtips dialogbox promptbox" id="jsComfirmDialig">
        <h1>确认提交</h1>
        <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
        <div class="cont">
            <h2>您确认提交吗？</h2>
            <dd class="autoTxtCount">
                <div class="button">
                    <input type="button" class="fl half-btn" value="确定" id="jsComfirmBtn"/>
                    <span class="fr half-btn jsCloseDialog">取消</span>
                </div>
            </dd>
        </div>
    </div>


</div>
<div class="bg" id="dialogBg"></div>

<script src="{% static 'js/deco-user.js' %}"></script>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>

<script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
<script src="{% static 'js/validate.js' %}" type="text/javascript"></script>
<script>
 var start = {

  elem: '#birthday',//选择ID为START的input
  event:'click',
  format: 'YYYY-MM-DD',//自动生成的时间格式
  istime: true,//必须填入时间
  istoday: false, //是否是当天
  start: laydate.now(0,"YYYY-MM-DD"), //设置开始时间为当前时间

  choose: function(datas){
    end.min = datas; //开始日选好后，重置结束日的最小日期
    end.start = datas //将结束日的初始值设定为开始日

  }

 };
 laydate(start)
</script>
{% block custom_js %}
{% endblock %}

</body>
</html>